package com.edupractice.malaria.modules.common.dao;

import com.edupractice.malaria.modules.common.pojo.Indicator;

public interface IndicatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer indicatorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbggenerated
     */
    int insert(Indicator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbggenerated
     */
    int insertSelective(Indicator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbggenerated
     */
    Indicator selectByPrimaryKey(Integer indicatorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Indicator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Indicator record);
}