package com.edupractice.malaria.modules.common.pojo;

public class Indicator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indicator.indicator_id
     *
     * @mbggenerated
     */
    private Integer indicatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indicator.field_name
     *
     * @mbggenerated
     */
    private String fieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indicator.belong_table
     *
     * @mbggenerated
     */
    private String belongTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indicator.table_alias
     *
     * @mbggenerated
     */
    private String tableAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indicator.display_name
     *
     * @mbggenerated
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indicator.downable
     *
     * @mbggenerated
     */
    private Byte downable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indicator.category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indicator.indicator_id
     *
     * @return the value of indicator.indicator_id
     *
     * @mbggenerated
     */
    public Integer getIndicatorId() {
        return indicatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indicator.indicator_id
     *
     * @param indicatorId the value for indicator.indicator_id
     *
     * @mbggenerated
     */
    public void setIndicatorId(Integer indicatorId) {
        this.indicatorId = indicatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indicator.field_name
     *
     * @return the value of indicator.field_name
     *
     * @mbggenerated
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indicator.field_name
     *
     * @param fieldName the value for indicator.field_name
     *
     * @mbggenerated
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indicator.belong_table
     *
     * @return the value of indicator.belong_table
     *
     * @mbggenerated
     */
    public String getBelongTable() {
        return belongTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indicator.belong_table
     *
     * @param belongTable the value for indicator.belong_table
     *
     * @mbggenerated
     */
    public void setBelongTable(String belongTable) {
        this.belongTable = belongTable == null ? null : belongTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indicator.table_alias
     *
     * @return the value of indicator.table_alias
     *
     * @mbggenerated
     */
    public String getTableAlias() {
        return tableAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indicator.table_alias
     *
     * @param tableAlias the value for indicator.table_alias
     *
     * @mbggenerated
     */
    public void setTableAlias(String tableAlias) {
        this.tableAlias = tableAlias == null ? null : tableAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indicator.display_name
     *
     * @return the value of indicator.display_name
     *
     * @mbggenerated
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indicator.display_name
     *
     * @param displayName the value for indicator.display_name
     *
     * @mbggenerated
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indicator.downable
     *
     * @return the value of indicator.downable
     *
     * @mbggenerated
     */
    public Byte getDownable() {
        return downable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indicator.downable
     *
     * @param downable the value for indicator.downable
     *
     * @mbggenerated
     */
    public void setDownable(Byte downable) {
        this.downable = downable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indicator.category
     *
     * @return the value of indicator.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indicator.category
     *
     * @param category the value for indicator.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }
}